services:
  - type: web
    name: docmind-rag
    env: docker
    plan: free
    region: ohio
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 8000
    autoDeploy: true
